apiVersion: v1
kind: Service
metadata:
  name: ivorysaga-nodeport-svc
  labels:
    name: ivorysaga
spec:
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 32666
  selector:
    app: ivorysaga

